### ISSUE TITLE
Client.__init__() got an unexpected keyword argument 'proxies'

### ISSUE THREAD

**Issue by web11-ateves** [andrewyng/aisuite#110]
When trying to use anthropic models I get this error.

Bellow you can find my requirements.txt

-i https://pypi.org/simple
aisuite[all]==0.1.6
annotated-types==0.7.0
anthropic==0.30.1
anyio==4.6.2.post1
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.4.0
cryptography==44.0.0
deprecated==1.2.15
distro==1.9.0
exceptiongroup==1.2.2
filelock==3.16.1
fsspec==2024.10.0
groq==0.9.0
h11==0.14.0
httpcore==1.0.7
httpx==0.28.0
huggingface-hub==0.26.3
idna==3.10
jiter==0.8.0
openai==1.55.3
packaging==24.2
pycparser==2.22
pydantic==2.10.2
pydantic-core==2.27.1
pygithub==2.5.0
pyjwt[crypto]==2.10.1
pynacl==1.5.0
python-dotenv==1.0.1
pyyaml==6.0.2
regex==2024.11.6
requests==2.32.3
sniffio==1.3.1
tiktoken==0.8.0
tokenizers==0.21.0
tqdm==4.67.1
typing-extensions==4.12.2
unidiff==0.7.5
urllib3==2.2.3
wrapt==1.17.0

**Comment by ksolo** [comment]
@web11-ateves Can you provide the sample code and the stack trace for the error?

**Comment by web11-ateves** [comment]
Sure! I’ve created a very basic example where the problem can be consistently reproduced.

My original code was designed for GitHub Actions, which is why you’ll notice the `INPUT_` variables at the beginning of the file.

You can find the example here: https://gist.github.com/web11-ateves/85eab94438249f90c9f19e26381ca63d

To reproduce the issue, simply modify the `.env` file, switching between OpenAI (which works) and Anthropic.

I noticed aisuite has a dependency on anthropic sdk v.0.30.1, but since then they have upgraded to v.0.40.0. Could this be related to the problem?

------

Strack trace bellow:

Traceback (most recent call last):
  File "/app/main.py", line 54, in <module>
    main()
  File "/app/main.py", line 47, in main
    response = send_to_openai(prompt = "Testing...", provider=OPENAI_API_PROVIDER, model=OPENAI_API_MODEL)
  File "/app/main.py", line 26, in send_to_openai
    response = client.chat.completions.create(
  File "/usr/local/lib/python3.10/site-packages/aisuite/client.py", line 108, in create
    self.client.providers[provider_key] = ProviderFactory.create_provider(
  File "/usr/local/lib/python3.10/site-packages/aisuite/provider.py", line 46, in create_provider
    return provider_class(**config)
  File "/usr/local/lib/python3.10/site-packages/aisuite/providers/anthropic_provider.py", line 16, in __init__
    self.client = anthropic.Anthropic(**config)
  File "/usr/local/lib/python3.10/site-packages/anthropic/_client.py", line 121, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/site-packages/anthropic/_base_client.py", line 835, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/usr/local/lib/python3.10/site-packages/anthropic/_base_client.py", line 733, in __init__
    super().__init__(**kwargs)
TypeError: Client.__init__() got an unexpected keyword argument 'proxies'

**Comment by ksolo** [comment]
@web11-ateves The version change in the anthropic client could definitely be an issue, we'll need to take a look to confirm.

**Comment by jaglinux** [comment]
I hit the same issue with basic example provided under "Set up" https://github.com/andrewyng/aisuite
Same issue is reported in https://github.com/anthropics/anthropic-sdk-python/issues/766
Fix is to upgrade to latest anthropic version.
pip install anthropic --upgrade

pip list | grep anthropic      
anthropic          0.40.0

**Comment by web11-ateves** [comment]
@jaglinux the issue is that the current release of aisuite is locked to anthropic 0.30.1

**Comment by zhimin-z** [comment]
Any update on this?
