### ISSUE TITLE
Pip installer not working with Python=3.12.1

### ISSUE THREAD

**Issue by noahvandal** [andrewyng/aisuite#145]
This may be an issue on my config, but I don't think so. Anyways the pip installer is not working with Python-3.12.1. It works with Python3.10 and 3.12.7. 

`
$ python --version
Python 3.12.1

$ pip install aisuite[all]
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python <4.0,>=3.12; 0.1.1 Requires-Python <4.0,>=3.10; 0.1.2 Requires-Python <4.0,>=3.10; 0.1.3 Requires-Python <4.0,>=3.10; 0.1.4 Requires-Python <4.0,>=3.10; 0.1.5 Requires-Python <4.0,>=3.10; 0.1.6 Requires-Python <4.0,>=3.10
ERROR: Could not find a version that satisfies the requirement aisuite[all] (from versions: none)`

But with python 3.12.7:
`$ python --version
Python 3.12.7
$ pip install aisuite[all]
Requirement already satisfied: aisuite[all] in c:\users\noahv\anaconda3\envs\voiceagent\lib\site-packages (0.1.6)
`

it works fine

**Comment by derekl-beep** [comment]
The installation works fine on macOS with Python 3.12.1. Here's the setup I used:

```
$ python --version                    
Python 3.12.1
$ pip install 'aisuite[all]'
Requirement already satisfied: aisuite[all] in ./venv/lib/python3.12/site-packages (0.1.6)
...
```

It might be worth updating pip to the latest for issues like this.
```
$ pip install -U pip 
```

**Comment by noahvandal** [comment]
Was able to reset my env and the issue was resolved. Thank you!

**Comment by noahvandal** [comment]
Was resolved when restarting all terminal clients.
