### ISSUE TITLE
Not able to use hugginfaceproviders for mistral and other models 

### ISSUE THREAD

**Issue by GauravKasat** [andrewyng/aisuite#88]
Getting error
LLMError: Hugging Face request failed: Client error '400 Bad Request' for url 'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.3/v1/chat/completions'

This was the piece of code that I tried

    response = client.chat.completions.create(
        model='huggingface:mistralai/Mistral-7B-Instruct-v0.3',
        messages=messages,
        temperature=0.75
    )
    print(response.choices[0].message.content)

**Comment by kvankova** [comment]
How did you implemented `messages`? When I tried the same with the example 
```
messages = [
    {"role": "system", "content": "You are a helpful agent, who answers with brevity."},
    {"role": "user", "content": 'Hi'},
]
```
it worked well for me. Given you received a 400 Bad Request error, it will probably be something with the `messages` argument.

**Comment by GauravKasat** [comment]
messages = [
    {"role": "system", "content": "Respond in Pirate English."},
    {"role": "user", "content": "Tell me a joke."},
]

**Comment by GauravKasat** [comment]
@kvankova  can you share your script?

**Comment by kvankova** [comment]
oh nice:) glad it works now
